/**
 * Auto-generated by `vigiles generate-types`.
 * DO NOT EDIT — re-run `vigiles generate-types` to update.
 */

declare module "vigiles/generated" {

  /** 3 npm scripts from package.json. */
  export type NpmScript = "lint:skills" | "lint:skills:fix" | "lint:skills:strict";

  /** 27 project files. */
  export type ProjectFile = 
    | "src/test/kotlin/registration/helpers/JwtHelper.kt"
    | "src/test/kotlin/registration/helpers/MockRegistrationServer.kt"
    | "src/test/kotlin/registration/helpers/MockServerExtension.kt"
    | "src/test/kotlin/registration/helpers/RegistrationHelper.kt"
    | "src/test/kotlin/registration/helpers/RegistrationMockServer.kt"
    | "src/test/kotlin/registration/helpers/TestData.kt"
    | "src/test/kotlin/registration/requests/RegisterApiClient.kt"
    | "src/test/kotlin/registration/requests/RegisterModels.kt"
    | "src/test/kotlin/registration/tests/RegistrationBvaTests.kt"
    | "src/test/kotlin/registration/tests/RegistrationCriticalTests.kt"
    | "src/test/kotlin/registration/tests/RegistrationIdempotencyTests.kt"
    | "src/test/kotlin/registration/tests/RegistrationL10nTests.kt"
    | "src/test/kotlin/registration/tests/RegistrationNegConflictTests.kt"
    | "src/test/kotlin/registration/tests/RegistrationNegNameTests.kt"
    | "src/test/kotlin/registration/tests/RegistrationNegPasswordTests.kt"
    | "src/test/kotlin/registration/tests/RegistrationNegValidationTests.kt"
    | "src/test/kotlin/registration/tests/RegistrationPositiveTests.kt"
    | "src/test/kotlin/registration/tests/RegistrationSecurityTests.kt"
    | "src/test/kotlin/registration/tests/RegistrationServiceFailureTests.kt"
    | "src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension"
    | "src/test/resources/junit-platform.properties"
    | "src/test/resources/schemas/register_201.json"
    | "src/test/resources/screenshots/brazil_passenger_main_screen/analysis-report.html"
    | "src/test/resources/screenshots/brazil_passenger_main_screen/analysis-report_20260226_000000.html"
    | "src/test/resources/screenshots/brazil_passenger_main_screen/ar_BR.png"
    | "src/test/resources/screenshots/brazil_passenger_main_screen/en_BR.png"
    | "src/test/resources/screenshots/brazil_passenger_main_screen/ru_BR.png";
}

declare module "vigiles/spec" {
  interface KnownProjectFiles {
    files: 
      | "src/test/kotlin/registration/helpers/JwtHelper.kt"
      | "src/test/kotlin/registration/helpers/MockRegistrationServer.kt"
      | "src/test/kotlin/registration/helpers/MockServerExtension.kt"
      | "src/test/kotlin/registration/helpers/RegistrationHelper.kt"
      | "src/test/kotlin/registration/helpers/RegistrationMockServer.kt"
      | "src/test/kotlin/registration/helpers/TestData.kt"
      | "src/test/kotlin/registration/requests/RegisterApiClient.kt"
      | "src/test/kotlin/registration/requests/RegisterModels.kt"
      | "src/test/kotlin/registration/tests/RegistrationBvaTests.kt"
      | "src/test/kotlin/registration/tests/RegistrationCriticalTests.kt"
      | "src/test/kotlin/registration/tests/RegistrationIdempotencyTests.kt"
      | "src/test/kotlin/registration/tests/RegistrationL10nTests.kt"
      | "src/test/kotlin/registration/tests/RegistrationNegConflictTests.kt"
      | "src/test/kotlin/registration/tests/RegistrationNegNameTests.kt"
      | "src/test/kotlin/registration/tests/RegistrationNegPasswordTests.kt"
      | "src/test/kotlin/registration/tests/RegistrationNegValidationTests.kt"
      | "src/test/kotlin/registration/tests/RegistrationPositiveTests.kt"
      | "src/test/kotlin/registration/tests/RegistrationSecurityTests.kt"
      | "src/test/kotlin/registration/tests/RegistrationServiceFailureTests.kt"
      | "src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension"
      | "src/test/resources/junit-platform.properties"
      | "src/test/resources/schemas/register_201.json"
      | "src/test/resources/screenshots/brazil_passenger_main_screen/analysis-report.html"
      | "src/test/resources/screenshots/brazil_passenger_main_screen/analysis-report_20260226_000000.html"
      | "src/test/resources/screenshots/brazil_passenger_main_screen/ar_BR.png"
      | "src/test/resources/screenshots/brazil_passenger_main_screen/en_BR.png"
      | "src/test/resources/screenshots/brazil_passenger_main_screen/ru_BR.png";
  }
  interface KnownNpmScripts {
    scripts: "lint:skills" | "lint:skills:fix" | "lint:skills:strict";
  }
}
